export const studyDict = {
  title: '시험 문제 풀기',
  subtitle: '2026 표준교재 기반 출제기준 객관식 문제 연습',
  navTitle: '문제 풀기',
  modes: {
    diagnostic: {
      id: 'DIAGNOSTIC' as const,
      title: '실력 진단',
      subtitle: '기본 점검 (힌트 없음)',
      description: '과목별 대표 문제를 풀며 현재 이해도와 취약 범위를 확인합니다. (힌트 미제공)',
      badge: '진단',
      defaultCount: 6,
    },
    improvement: {
      id: 'IMPROVEMENT' as const,
      title: '취약 보강',
      subtitle: '핵심 힌트 및 개념 정리',
      description: '취약 영역을 집중 보강합니다. 문제 풀이 전 교재 핵심 요약 힌트를 확인할 수 있습니다.',
      badge: '추천',
      defaultCount: 5,
    },
    mockExam: {
      id: 'MOCK_EXAM' as const,
      title: '실전 점검',
      subtitle: '모의고사 (과목별 배분)',
      description: '출제기준 과목 배분을 반영한 모의고사 세션입니다. (힌트 미제공, 실전 연습)',
      badge: '실전',
      defaultCount: 10,
    },
  },
  card: {
    questionLabel: '문항',
    hintButton: '💡 핵심 힌트 보기',
    hintLoading: '힌트 불러오는 중...',
    hintTitle: '💡 핵심 개념 정리',
    submitButton: '정답 제출',
    submitting: '채점 중...',
    nextButton: '다음 문제 →',
    correctBadge: '정답',
    incorrectBadge: '오답',
    explanationTitle: '해설 및 출제 근거',
    sourceLabel: '출처 보기',
    selectOptionPrompt: '보기를 선택해주세요.',
    optionPrefix: ['①', '②', '③', '④'],
  },
  session: {
    startSession: '학습 시작하기',
    progress: (current: number, total: number) => `${current} / ${total} 문항`,
    progressTitle: '학습 진행률',
    completeTitle: '학습 세션 완료',
    completeSubtitle: '수고하셨습니다! 이번 세션의 풀이 결과입니다.',
    scoreLabel: '최종 점수',
    accuracyLabel: '정답률',
    restartButton: '새 학습 시작',
    modeLabel: '학습 모드',
    loadingSession: '학습 문제를 불러오는 중입니다...',
    errorLoading: '문제를 불러오는 중 오류가 발생했습니다.',
    emptySession: '세션에 남은 문제가 없습니다.',
  },
} as const
