export const studyDict = {
  title: 'RAG 적응형 문제 학습',
  subtitle: '금융투자협회 2026 표준교재 기반 1문항 단위 적응형 객관식 학습',
  navTitle: '문제 풀기',
  modes: {
    diagnostic: {
      id: 'DIAGNOSTIC' as const,
      title: '실력 체크',
      subtitle: '초기 진단용 (힌트 없음)',
      description: '세부과목별 최소 표본을 한 문제씩 풀며 현재 실력과 보완이 필요한 범위를 진단합니다. (힌트 미제공)',
      badge: '진단',
      defaultCount: 6,
    },
    improvement: {
      id: 'IMPROVEMENT' as const,
      title: '실력 향상',
      subtitle: 'AI 힌트 및 적응형 피드백',
      description: '취약 영역과 최근 오답을 집중 보강합니다. 문제 풀이 전 AI 개념 설명 및 힌트를 활용할 수 있습니다.',
      badge: '추천',
      defaultCount: 5,
    },
    mockExam: {
      id: 'MOCK_EXAM' as const,
      title: '시험 점검',
      subtitle: '모의고사 쿼터 (과목별 배분)',
      description: '출제기준 과목 배분을 반영한 모의고사 세션입니다. (힌트 미제공, 실전 연습)',
      badge: '실전',
      defaultCount: 10,
    },
  },
  card: {
    questionLabel: '문항',
    hintButton: '💡 AI 힌트 요청',
    hintLoading: '힌트 생성 중...',
    hintTitle: '💡 핵심 개념 힌트',
    submitButton: '정답 제출',
    submitting: '채점 중...',
    nextButton: '다음 문제 진행 →',
    correctBadge: '정답',
    incorrectBadge: '오답',
    explanationTitle: '해설 및 개념 근거',
    sourceLabel: '출처 보기',
    selectOptionPrompt: '보기를 선택해주세요.',
    optionPrefix: ['①', '②', '③', '④'],
  },
  session: {
    startSession: '학습 시작하기',
    progress: (current: number, total: number) => `${current} / ${total} 문항`,
    progressTitle: '학습 진행률',
    completeTitle: '학습 세션 완료',
    completeSubtitle: '수고하셨습니다! 이번 세션의 풀이 결과입니다.',
    scoreLabel: '최종 점수',
    accuracyLabel: '정답률',
    restartButton: '새 학습 시작',
    modeLabel: '학습 모드',
    loadingSession: '학습 문제를 불러오는 중입니다...',
    errorLoading: '문제를 불러오는 중 오류가 발생했습니다.',
    emptySession: '세션에 남은 문제가 없습니다.',
  },
} as const
